### ISSUE TITLE
[Bug]: sync failure

### ISSUE THREAD

**Issue by atomGit** [GetPublii/Publii#1255]
### Operating system

manjaro

### Publii version

0.43.0 (build 16368)

### Post editor

None

### Bug description

this happened after syncing several times and without changing any sync or ssh settings

deployment-errors.log ...

```
(node:31982) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `Publii --trace-warnings ...` to show where the warning was created)
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: Client public key size is invalid]

Node.js v18.16.1
```

i restarted publii after which the sync went ok

### Steps to reproduce

sync to remote, sftp with ssh keys

**Comment by cbleek** [comment]
Maybe i have the same Problem. Running 

```
C:\Users\Baieyu>AppData\Local\Programs\Publii\Publii.exe --trace-warnings

C:\Users\Baieyu>
(node:8072) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
    at emitWarning (C:\Users\Baieyu\AppData\Local\Programs\Publii\resources\app.asar\node_modules\aws-sdk\lib\maintenance_mode_message.js:37:13)
    at Timeout._onTimeout (C:\Users\Baieyu\AppData\Local\Programs\Publii\resources\app.asar\node_modules\aws-sdk\lib\maintenance_mode_message.js:45:5)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
Set spellchecker to: de
```

I get the error message right after starting Publii on the console. 


![image](https://github.com/GetPublii/Publii/assets/858642/c374d00d-4c82-4081-9692-2dbddc03c8ba)
