### ISSUE TITLE
[Bug]: TypeError: item.replace is not a function

### ISSUE THREAD

**Issue by delirehberi** [GetPublii/Publii#1303]
### Operating system

macOS Sonoma 14

### Publii version

0.44.1 (build 16519)

### Post editor

None

### Bug description

I am trying to import 1700 post from wordpress to publii. Everytime it stucks in a spesific post. Attached import-error.log file. I believe there is corrupted tag in there. It will be resolved after updating [that line](https://github.com/GetPublii/Publii/blob/master/app/back-end/post.js#L462) like this: 

```js
tagsToSave = tagsToSave.filter(function (item) {
                if(typeof item != 'string') return false;
                return item.replace(/\s/g, '') !== '';
            });
```

### Relevant log output

```shell
/Applications/Publii.app/Contents/Resources/app.asar/back-end/post.js:462
                return item.replace(/\s/g, '') !== '';
                            ^

TypeError: item.replace is not a function
    at /Applications/Publii.app/Contents/Resources/app.asar/back-end/post.js:462:29
    at Array.filter (<anonymous>)
    at Post.saveTags (/Applications/Publii.app/Contents/Resources/app.asar/back-end/post.js:461:37)
    at Post.save (/Applications/Publii.app/Contents/Resources/app.asar/back-end/post.js:249:14)
    at WxrParser.importPostsData (/Applications/Publii.app/Contents/Resources/app.asar/back-end/modules/import/wxr-parser.js:432:41)
    at Import.importFile (/Applications/Publii.app/Contents/Resources/app.asar/back-end/modules/import/import.js:93:21)
    at process.<anonymous> (/Applications/Publii.app/Contents/Resources/app.asar/back-end/workers/import/import.js:14:18)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

Node.js v18.16.1
```

**Comment by dziudek** [comment]
Hi,

Thank you for spotting this - fix will be added in v.0.44.2
