### ISSUE TITLE
[Bug]: Cannot upload website via FTP, FTPS or SFTP

### ISSUE THREAD

**Issue by Uzayer** [GetPublii/Publii#1417]
### Operating system

macOS 14.3.1 (23D60)

### Publii version

0.45.1 (build 16608)

### Post editor

None

### Bug description

Using FTP services like Cyberduck works perfectly fine on the server. The same information was given to Publii, but the upload does not work. Test connection shows everything is fine but the sync website upload does not work.

### Relevant log output

```shell
[Wed, 06 Mar 2024 12:58:09 GMT] ERR (2): Error: get: No such file /public_html/files.publii.json (Error: get: No such file /public_html/files.publii.json
    at SftpClient.fmtError (/Applications/Publii.app/Contents/Resources/app.asar/node_modules/ssh2-sftp-client/src/index.js:87:22)
    at ReadStream.<anonymous> (/Applications/Publii.app/Contents/Resources/app.asar/node_modules/ssh2-sftp-client/src/index.js:507:23)
    at Object.onceWrapper (node:events:632:26)
    at ReadStream.emit (node:events:517:28)
    at Object.cb (/Applications/Publii.app/Contents/Resources/app.asar/node_modules/ssh2/lib/protocol/SFTP.js:3710:12)
    at 101 (/Applications/Publii.app/Contents/Resources/app.asar/node_modules/ssh2/lib/protocol/SFTP.js:2858:11)
    at SFTP.push (/Applications/Publii.app/Contents/Resources/app.asar/node_modules/ssh2/lib/protocol/SFTP.js:278:11)
    at CHANNEL_DATA (/Applications/Publii.app/Contents/Resources/app.asar/node_modules/ssh2/lib/client.js:587:23)
    at 94 (/Applications/Publii.app/Contents/Resources/app.asar/node_modules/ssh2/lib/protocol/handlers.misc.js:930:16)
    at Protocol.onPayload (/Applications/Publii.app/Contents/Resources/app.asar/node_modules/ssh2/lib/protocol/Protocol.js:2059:10)) [<- files.publii.json]
Founded 282 operations to do
[Wed, 06 Mar 2024 12:58:10 GMT] ERROR UPLOAD DIR: /public_html/tags
[Wed, 06 Mar 2024 12:58:10 GMT] Error: mkdir: _doMkdir: Permission denied /public_html
[Wed, 06 Mar 2024 12:58:10 GMT] ERROR UPLOAD DIR: /public_html/media
[Wed, 06 Mar 2024 12:58:10 GMT] Error: mkdir: _doMkdir: Permission denied /public_html
[Wed, 06 Mar 2024 12:58:11 GMT] ERROR UPLOAD DIR: /public_html/apply
[Wed, 06 Mar 2024 12:58:11 GMT] Error: mkdir: _doMkdir: Permission denied /public_html
```

**Comment by internettips** [comment]
@Uzayer 

Hi, just for info / reference purposes ... I'm using the exact same operating system and Publii versions and builds, as you, plus my setup is SFTP (with key) and website upload, synch, etc., works just fine. My web host, in this instance, is SiteGround.com.

**Comment by dziudek** [comment]
Hi,

Most probably your "Path" option is configured wrongly - most probably you have to use the absolute path to the destination directory

**Comment by internettips** [comment]
@Uzayer @dziudek 

When configuring my SFTP setup, when I followed my web host's instruction, I needed to change the Port to: 18765

Also, as @dziudek suggested, the precise Remote path was crucial. In my instance, it would be: 
/home/customer/www/your-domain-name.com/public_html/

Hope that helps.

**Comment by jeckyl** [comment]
FTP, SFTP, Archive ... same problem here.
Impossible to export the site.

**Comment by meika** [comment]
Just trying to understand what "precise remote path" might be ???
```
somedomain.com/public_html/ 
ftp.somedomain.com/public_html/
```
Publii Version: 0.42.1 (build 16233) on NixOS (so its the nixOS package and not very recent by the look)

filezilla works fine, but uploading the zip file will get more and more onerous.

**Comment by keomabrun** [comment]
Hi :wave: 

I have a similar issue.

![image](https://github.com/user-attachments/assets/db9e5ed0-1de0-4d76-bf53-aa7a9220562c)

I am using Publiii version 0.46.1 (build 16918) on MintOS.
Filezilla works fine too.

I have tried relative and absolute paths, with and without slashes.

I don't see error message in the CLI though, so I'm not sure this is exactly the same error.

**Comment by meika** [comment]
Keep trying various file pathway variations, mine ended up being the simplest one, not the complex longer versions
somedomain.com 
not
somedomain.com/username/public/subdomain/home/.... (or whatever you've got)(serving suggestions are exaggerated for effect)

apparently it varies a lot by hosting provider and whatever guesswork is in the middle by Publii

when it finally worked I was shocked, there is no clear help on this unfortunately, even contacting my friendly hosting provider was not particular helpful, but start with the simplest and see how you go

**Comment by marcpley** [comment]
Hello. I work with keomabrun on the same issue.
I tryed various file pathway variations. Sometime Publii say the connection is successful, sometime it say that the connection is successful but it is unable to store files. Both case with the same parameters ! After that, in any cases, the "Save settings" button is  active but do nothing, so I cannot jump to site files uploading step.

**Comment by philazerty** [comment]
Hello
Same problem for me. The connection works but I can't send any files.
In the Publii's logs :
`[parser] < '501 PASV: Operation not permitted\r\n'
[Thu, 28 Nov 2024 10:12:35 GMT] [parser] Response: code=501, buffer='PASV: Operation not permitted'`
Yet it works with filezilla in passive mode too.
An idea ?

**Comment by dziudek** [comment]
@philazerty - please go to the App settings -> Experimental features -> please enable both options and then restart app and try again (you must to enable both options, as due mistake the first option is used to enable alternative FTP library which supports IPv6 - it will be fixed in v.0.46.3)

**Comment by philazerty** [comment]
> @philazerty - please go to the App settings -> Experimental features -> please enable both options and then restart app and try again (you must to enable both options, as due mistake the first option is used to enable alternative FTP library which supports IPv6 - it will be fixed in v.0.46.3)

Thanks @dziudek 
But it doesn't work any better. Still can't load a file. No problem with Filezilla
Any other ideas?
Thanks

**Comment by dziudek** [comment]
@philazerty - do you have the same error in logs?

**Comment by bttrx** [comment]
@dziudek I experienced the same problem as @philazerty and enabling both experimental features and restarting Publii fixed it for me. Thanks!

**Comment by philazerty** [comment]
@dziudek : My problem is solved by update to Publii 0.46.3 ! 
Many thanks for your support !

**Comment by Mickael-Martin** [comment]
Same issue for me for OVH website.

**Comment by dziudek** [comment]
@TheRealBeef - what about your server configuration - did you specified something in the remote path option? I am asking, because I have made few uploads and sync using the alternative FTP library and it works. Also - are you using the latest Publii version?

**Comment by Lekain** [comment]
Same problem as described before. Connection to the server is working, but it is impossible to send files. Experimental features do not change anything. I use 0.48.5 with Mac Silicon. Any help would be appreciated.

**Comment by hkremer** [comment]
I could solve it by using a ssh key file in stead of the password option.

**Comment by Lekain** [comment]
All my fault. The password system had changed on the server, and I was not aware of it. Publii still works like a charm now.
