### ISSUE TITLE
WP Importer - problem with non-latin tag slugs

### ISSUE THREAD

**Issue by dziudek** [GetPublii/Publii#164]
Non-latin chars in the tag slugs blocks the import process.

**Comment by typeetfunc** [comment]
@dziudek I has this error. v.0.31.3 (build 11117) Beta
Logs: 
/Applications/Publii.app/Contents/Resources/app/back-end/vendor/sql.js:5
1<process.argv.length?process.argv[1].replace(/\\/g,"/"):"unknown-program");f.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=f);process.on("uncaughtException",function(a){if(!(a instanceof la))throw a;});f.inspect=function(){return"[Emscripten Module object]"}}else if(ga)f.print||(f.print=print),"undefined"!=typeof printErr&&(f.printErr=printErr),f.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},f.readBinary=function(a){if("function"===
                                                                                                                                                                                                                               ^

Error: near "Династия": syntax error
    at a.handleError (/Applications/Publii.app/Contents/Resources/app/back-end/vendor/sql.js:494:377)
    at a.exec (/Applications/Publii.app/Contents/Resources/app/back-end/vendor/sql.js:492:57)
    at Tag.isTagNameUnique (/Applications/Publii.app/Contents/Resources/app/back-end/tag.js:146:31)
    at Tag.save (/Applications/Publii.app/Contents/Resources/app/back-end/tag.js:42:18)
    at WxrParser.createTag (/Applications/Publii.app/Contents/Resources/app/back-end/modules/import/wxr-parser.js:318:37)
    at WxrParser.importTagsData (/Applications/Publii.app/Contents/Resources/app/back-end/modules/import/wxr-parser.js:284:22)
    at Import.importFile (/Applications/Publii.app/Contents/Resources/app/back-end/modules/import/import.js:80:21)
    at process.<anonymous> (/Applications/Publii.app/Contents/Resources/app/back-end/workers/import/import.js:14:18)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)

Importer fails on this tag:
```
<wp:tag>
		<wp:term_id>240</wp:term_id>
		<wp:tag_slug><![CDATA[fond-dinastiya]]></wp:tag_slug>
		<wp:tag_name><![CDATA[Фонд "Династия"]]></wp:tag_name>
</wp:tag>
```

**Comment by typeetfunc** [comment]
@dziudek  Why do you not use something like https://github.com/mysqljs/sqlstring/blob/master/lib/SqlString.js in https://github.com/GetPublii/Publii/blob/8db728c848a7c2e8c15770d1fd96e7e38304a8dd/app/back-end/tag.js#L145 ?
