### ISSUE TITLE
[Bug]: WXR importer fails on invalid image source link

### ISSUE THREAD

**Issue by atkulp** [GetPublii/Publii#1725]
### Operating system

Windows 11

### Publii version

0.46.1 (build 16918)

### Post editor

None

### Bug description

Attempted to import a Wordpress export file and it imported all posts fine, but failed after a few images. I tracked it down to some image links (literally, the word "assets" was somehow in the src attribute). It errored out and crashed the importer.

### Steps to reproduce

Import from WXR file where some img src attributes are invalid.
No error appears, but import stops at the first instance.

### Relevant log output

```shell
node:internal/url:797
    this.#updateContext(bindingUrl.parse(input, base));
                                   ^

TypeError: Invalid URL
    at new URL (node:internal/url:797:36)
    at module.exports.image (C:\Users\arian\AppData\Local\Programs\Publii\resources\app.asar\node_modules\image-downloader\index.js:15:19)
    at WxrParser.downloadImages (C:\Users\arian\AppData\Local\Programs\Publii\resources\app.asar\back-end\modules\import\wxr-parser.js:726:22)
    at Timeout._onTimeout (C:\Users\arian\AppData\Local\Programs\Publii\resources\app.asar\back-end\modules\import\wxr-parser.js:749:26)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7) {
  code: 'ERR_INVALID_URL',
  input: 'assets'
}

Node.js v20.16.0
```

**Comment by dziudek** [comment]
@atkulp - in v.0.46.2 planned for next week Publii will check if image src attribute contains URL or path - if path, then the image won't be downloaded
