### ISSUE TITLE
[Bug]: Wordpress import fails on parsing/creating authors if file contains default username

### ISSUE THREAD

**Issue by atkulp** [GetPublii/Publii#1726]
### Operating system

Windows 11

### Publii version

0.46.1 (build 16918)

### Post editor

None

### Bug description

I tried to import a WXR file with multiple authors. It failed. On a hunch, I wondered if the "admin" user in my export might be causing a conflict with the default Publii user I created named "admin" (it shouldn't...) I did a search and replace in the file to change admin to admin2 and it started working. Here is the original form:

```
	<wp:author><wp:author_id>1</wp:author_id><wp:author_login><![CDATA[admin]]></wp:author_login><wp:author_email><![CDATA[admin@localhost.com]]></wp:author_email><wp:author_display_name><![CDATA[admin]]></wp:author_display_name><wp:author_first_name><![CDATA[]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>
	<wp:author><wp:author_id>2</wp:author_id><wp:author_login><![CDATA[damian-and-lilly]]></wp:author_login><wp:author_email><![CDATA[sd@ss.com]]></wp:author_email><wp:author_display_name><![CDATA[Damian and Lilly]]></wp:author_display_name><wp:author_first_name><![CDATA[Damian and Lilly]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>
	<wp:author><wp:author_id>4</wp:author_id><wp:author_login><![CDATA[arian-and-karen]]></wp:author_login><wp:author_email><![CDATA[sd@wd.com]]></wp:author_email><wp:author_display_name><![CDATA[Arian and Karen]]></wp:author_display_name><wp:author_first_name><![CDATA[Arian and Karen]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>
	<wp:author><wp:author_id>3</wp:author_id><wp:author_login><![CDATA[gabriel-and-kendrea]]></wp:author_login><wp:author_email><![CDATA[ss@sds.com]]></wp:author_email><wp:author_display_name><![CDATA[Gabriel and Kendrea]]></wp:author_display_name><wp:author_first_name><![CDATA[Gabriel and Kendrea]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>
```

### Steps to reproduce

Create a new site with default user named "admin" (or whatever)
Import a Wordpress WXR file containing the same user)
Check the "Import authors" option
Click Import data
Give up

### Relevant log output

```shell
C:\Users\arian\AppData\Local\Programs\Publii\resources\app.asar\back-end\modules\import\wxr-parser.js:263
        let newAuthorResultFiltered = authors.filter(author => author.username === authorUsername);
                                              ^

TypeError: Cannot read properties of undefined (reading 'filter')
    at WxrParser.createAuthor (C:\Users\arian\AppData\Local\Programs\Publii\resources\app.asar\back-end\modules\import\wxr-parser.js:263:47)
    at WxrParser.importAuthorsData (C:\Users\arian\AppData\Local\Programs\Publii\resources\app.asar\back-end\modules\import\wxr-parser.js:230:18)
    at Import.importFile (C:\Users\arian\AppData\Local\Programs\Publii\resources\app.asar\back-end\modules\import\import.js:96:21)
    at process.<anonymous> (C:\Users\arian\AppData\Local\Programs\Publii\resources\app.asar\back-end\workers\import\import.js:14:18)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

Node.js v20.16.0
```

**Comment by atkulp** [comment]
I think I just realized you specify your own default user for the site. Regardless, it's presence in an import file shouldn't cause a conflict.

**Comment by dziudek** [comment]
@atkulp problem will be fixed in v.0.46.2 - when username will be the same as the existing author - it will be used instead of trying to create a new one what lead to the described issue. Thank you for reporting this issue :)
