### ISSUE TITLE
[Bug]: Rendering process failed (value.replace is not a function)

### ISSUE THREAD

**Issue by x4740N** [GetPublii/Publii#1739]
### Operating system

Windows 11 Pro 23H2 Build: 22631.4112

### Publii version

0.46.1 (build 16918)

### Post editor

None

### Bug description

Error:

```
Rendering process failed
An error occurred during rendering process:

value.replace is not a function

TypeError: value.replace is not a function
    at tidyAtRule (C:\Users\nicholasj\AppData\Local\Programs\Publii\resources\app.asar\node_modules\clean-css\lib\optimizer\level-1\tidy-at-rule.js:3:6)
    at level1Optimize (C:\Users\nicholasj\AppData\Local\Programs\Publii\resources\app.asar\node_modules\clean-css\lib\optimizer\level-1\optimize.js:283:45)
    at optimize (C:\Users\nicholasj\AppData\Local\Programs\Publii\resources\app.asar\node_modules\clean-css\lib\clean.js:213:7)
    at C:\Users\nicholasj\AppData\Local\Programs\Publii\resources\app.asar\node_modules\clean-css\lib\clean.js:190:29
    at C:\Users\nicholasj\AppData\Local\Programs\Publii\resources\app.asar\node_modules\clean-css\lib\reader\read-sources.js:27:63
    at loadOriginalSources (C:\Users\nicholasj\AppData\Local\Programs\Publii\resources\app.asar\node_modules\clean-css\lib\reader\load-original-sources.js:26:7)
    at C:\Users\nicholasj\AppData\Local\Programs\Publii\resources\app.asar\node_modules\clean-css\lib\reader\read-sources.js:27:14
    at applySourceMaps (C:\Users\nicholasj\AppData\Local\Programs\Publii\resources\app.asar\node_modules\clean-css\lib\reader\apply-source-maps.js:34:7)
    at Object.callback (C:\Users\nicholasj\AppData\Local\Programs\Publii\resources\app.asar\node_modules\clean-css\lib\reader\read-sources.js:26:12)
    at doInlineImports (C:\Users\nicholasj\AppData\Local\Programs\Publii\resources\app.asar\node_modules\clean-css\lib\reader\read-sources.js:199:25)
```
For some reason publii refuses to preview my site since i added the following code to my custom css:

```
.CHCALI {
    border-radius: 7px;
    border-style: dashed;
    background-clip: padding-box;
    border-width: 1.5px;
    height: 250px;
    width: 200px;
}
```

I have similar code elsewhere in my custom css which is the same but only with a different class

Here is my entire custom css if relevant
```

/*
 * Put your custom CSS code here
 */

/*FOR JAPANESE YOUTUBE CHANNEL COLLECTION LINK BOX*/
.JP_ENYTSUB {
  /*background-image: linear-gradient(to right, blue, purple);*/
  /*background:grey*/
  border-radius: 7px;
  border-style: dashed;
  background-clip: padding-box;
  border-width: 1.5px;
  height: 250px;
  width: 200px;  
}


.JP_ENYTSUBTTEXTBOX {
  background:darkgray;
  opacity:85%;
  height:155px;
  margin-top: 93px;  
  border-bottom-left-radius: 7px;
  border-bottom-right-radius: 7px;
  text-align: center;
  /*z-index: -1;*/  
}

.JP_ENYTSUBHTEXT {
    z-index: 9;
}

.JP_ENYTSUBTTEXTBOXSUB {
  text-align: center;
  font-size: 10px;
}

.JP_ENYTSUB {
    background: linear-gradient(270deg, #ffffff, #bc002d, #ff0000);
    background-size: 600% 600%;
    background-clip: padding-box;

    -webkit-animation: AnimationName 30s ease infinite;
    -moz-animation: AnimationName 30s ease infinite;
    animation: AnimationName 30s ease infinite;
}

@-webkit-keyframes AnimationName {
    0%{background-position:0% 50%}
    50%{background-position:100% 50%}
    100%{background-position:0% 50%}
}
@-moz-keyframes AnimationName {
    0%{background-position:0% 50%}
    50%{background-position:100% 50%}
    100%{background-position:0% 50%}
}
@keyframes AnimationName {
    0%{background-position:0% 50%}
    50%{background-position:100% 50%}
    100%{background-position:0% 50%}
}

/*LOGO*/
/*.logo {
  width: 100px;
  height: 100px;
  border-style:dashed;
  border-radius:9000vh;
  padding-bottom: 104.5px;
}*/

/* PAGE BACKGROUND, HOPEFULLY*/

.page-template, .home-template {
    
}

@import compass


// n is number of stars required
@function multiple-box-shadow ($n) 
  $value: '#{random(2000)}px #{random(2000)}px #FFF'
  @for $i from 2 through $n
    $value: '#{$value} , #{random(2000)}px #{random(2000)}px #FFF'

  @return unquote($value)

$shadows-small:  multiple-box-shadow(700)
$shadows-medium: multiple-box-shadow(200)
$shadows-big:    multiple-box-shadow(100)

html
  height: 100%
  background: radial-gradient(ellipse at bottom, #1B2735 0%, #090A0F 100%)
  overflow: hidden
    
#stars
  width: 1px
  height: 1px
  background: transparent
  box-shadow: $shadows-small
  animation     : animStar 50s linear infinite
    
  &:after
    content: " "
    position: absolute
    top: 2000px
    width: 1px
    height: 1px
    background: transparent
    box-shadow: $shadows-small
    
#stars2
  width: 2px
  height: 2px
  background: transparent
  box-shadow: $shadows-medium
  animation     : animStar 100s linear infinite
    
  &:after
    content: " "
    position: absolute
    top: 2000px
    width: 2px
    height: 2px
    background: transparent
    box-shadow: $shadows-medium
    
#stars3
  width: 3px
  height: 3px
  background: transparent
  box-shadow: $shadows-big
  animation     : animStar 150s linear infinite
    
  &:after
    content: " "
    position: absolute
    top: 2000px
    width: 3px
    height: 3px
    background: transparent
    box-shadow: $shadows-big

#title
  position: absolute
  top: 50%
  left: 0
  right: 0
  
  color: #FFF
  text-align: center
  font-family: 'lato',sans-serif
  font-weight: 300
  font-size: 50px
  letter-spacing: 10px
  
  margin-top: -60px
  padding-left: 10px
  
  span
    background: -webkit-linear-gradient(white, #38495a)
    -webkit-background-clip: text
    -webkit-text-fill-color: transparent
    
@keyframes animStar
  from  
    transform: translateY(0px)
  to    
    transform: translateY(-2000px)
    
/*FOR GAOMON & HUION MANUAL CALIBRATION GUIDE LINK BOX*/

.CHCALI {
    border-radius: 7px;
    border-style: dashed;
    background-clip: padding-box;
    border-width: 1.5px;
    height: 250px;
    width: 200px;
}
```
Ive noticed that if i remove the code i added for "GHCALI" then the problem goes away

Publii also seems to keep the text green instead of making it black
    

### Steps to reproduce

Enter custom CSS code like described in issue

Sorry i cant be more specific

**Comment by x4740N** [comment]
Hello, anyone there

**Comment by bjazmoore** [comment]
Maybe it is a namespace collision.  Can you slightly modify the class name?  Does that make a difference?

What happens when you comment out all the lines of CSS for the class?  Same issue?  Now add one back at a time.

**Comment by dziudek** [comment]
@x4740N - your issue is related to fact that you have put SCSS code to the custom CSS - please remove:

```
@import compass


// n is number of stars required
@function multiple-box-shadow ($n) 
  $value: '#{random(2000)}px #{random(2000)}px #FFF'
  @for $i from 2 through $n
    $value: '#{$value} , #{random(2000)}px #{random(2000)}px #FFF'

  @return unquote($value)

$shadows-small:  multiple-box-shadow(700)
$shadows-medium: multiple-box-shadow(200)
$shadows-big:    multiple-box-shadow(100)

html
  height: 100%
  background: radial-gradient(ellipse at bottom, #1B2735 0%, #090A0F 100%)
  overflow: hidden
    
#stars
  width: 1px
  height: 1px
  background: transparent
  box-shadow: $shadows-small
  animation     : animStar 50s linear infinite
    
  &:after
    content: " "
    position: absolute
    top: 2000px
    width: 1px
    height: 1px
    background: transparent
    box-shadow: $shadows-small
    
#stars2
  width: 2px
  height: 2px
  background: transparent
  box-shadow: $shadows-medium
  animation     : animStar 100s linear infinite
    
  &:after
    content: " "
    position: absolute
    top: 2000px
    width: 2px
    height: 2px
    background: transparent
    box-shadow: $shadows-medium
    
#stars3
  width: 3px
  height: 3px
  background: transparent
  box-shadow: $shadows-big
  animation     : animStar 150s linear infinite
    
  &:after
    content: " "
    position: absolute
    top: 2000px
    width: 3px
    height: 3px
    background: transparent
    box-shadow: $shadows-big

#title
  position: absolute
  top: 50%
  left: 0
  right: 0
  
  color: #FFF
  text-align: center
  font-family: 'lato',sans-serif
  font-weight: 300
  font-size: 50px
  letter-spacing: 10px
  
  margin-top: -60px
  padding-left: 10px
  
  span
    background: -webkit-linear-gradient(white, #38495a)
    -webkit-background-clip: text
    -webkit-text-fill-color: transparent
    
@keyframes animStar
  from  
    transform: translateY(0px)
  to    
    transform: translateY(-2000px)
    
 ```
