### ISSUE TITLE
[Bug]: generating preview or syncing results in Rendering process fail

### ISSUE THREAD

**Issue by raramuridesign** [GetPublii/Publii#1900]
### Operating system

Win 11

### Publii version

0.4.63 build 17008

### Post editor

None

### Bug description

The following error shows when doing a preview or syncing a site.

```
Rendering process failed
An error occurred during rendering process:

The partial head could not be found

Error: The partial head could not be found
    at Object.invokePartial (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\node_modules\handlebars\dist\cjs\handlebars\runtime.js:332:11)
    at Object.invokePartialWrapper [as invokePartial] (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\node_modules\handlebars\dist\cjs\handlebars\runtime.js:84:39)
    at Object.eval [as main] (eval at createFunctionContext (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:262:23), :10:31)
    at main (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\node_modules\handlebars\dist\cjs\handlebars\runtime.js:208:32)
    at ret (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\node_modules\handlebars\dist\cjs\handlebars\runtime.js:212:12)
    at ret (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:519:21)
    at Renderer.generateFrontpage (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\back-end\modules\render-html\renderer.js:875:26)
    at Renderer.generateWWW (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\back-end\modules\render-html\renderer.js:238:18)
    at Renderer.renderFullPreview (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\back-end\modules\render-html\renderer.js:193:20)
    at Renderer.renderSite (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\back-end\modules\render-html\renderer.js:174:28)
```

### Steps to reproduce

1. Install new version 0.4.63 build 17008
2. Make a change to pages / posts
3. Save template and or site settings
4. Sync or preview

**Comment by dziudek** [comment]
@raramuridesign - thank you for reporting this - I have prepared a hot fix - @bobmitro will sign it and release a new package in a few nearest hours

**Comment by bobmitro** [comment]
Please refer to the same thread thread: https://github.com/GetPublii/Publii/discussions/1899

**Comment by FLMMFL** [comment]
same issue after upgrading the application this morning.

**Comment by raramuridesign** [comment]
@bobmitro @dziudek  I have just tested on the new build - I get this error. See below
I also checked the version of the app, and it still sais 17008 --- is there a way to force to 17009 ? 

`Rendering process failed
An error occurred during rendering process:

The partial head could not be found

```
Error: The partial head could not be found
    at Object.invokePartial (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\node_modules\handlebars\dist\cjs\handlebars\runtime.js:332:11)
    at Object.invokePartialWrapper [as invokePartial] (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\node_modules\handlebars\dist\cjs\handlebars\runtime.js:84:39)
    at Object.eval [as main] (eval at createFunctionContext (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:262:23), <anonymous>:10:31)
    at main (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\node_modules\handlebars\dist\cjs\handlebars\runtime.js:208:32)
    at ret (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\node_modules\handlebars\dist\cjs\handlebars\runtime.js:212:12)
    at ret (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:519:21)
    at Renderer.generateFrontpage (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\back-end\modules\render-html\renderer.js:875:26)
    at Renderer.generateWWW (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\back-end\modules\render-html\renderer.js:238:18)
    at Renderer.renderFullPreview (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\back-end\modules\render-html\renderer.js:193:20)
    at Renderer.renderSite (C:\Users\matth\AppData\Local\Programs\Publii\resources\app.asar\back-end\modules\render-html\renderer.js:174:28)

```

**Comment by bobmitro** [comment]
Maybe th browser cache, clear and download again.

**Comment by raramuridesign** [comment]
![image](https://github.com/user-attachments/assets/8736eadf-25ca-4d7e-a27e-14afb0ec3c93)

Awesome, previous file was cached. 

Have a super festive season.

**Comment by bobmitro** [comment]
U too.
