### ISSUE TITLE
Startup on MacOS BigSur version 11.1 produces error

### ISSUE THREAD

**Issue by derintolu** [GetPublii/Publii#905]
Uncaught Exception:
Error: ENOENT: no such file or directory, scandir '/Users/derin/Documents/Publii/sites'
at Object.readdirSync (fs.js:854:3)
at Object.fs.readdirSync (electron/js2c/asar.js:621:39)
at App.loadSites (/Applications/Publii.app/Contents/Resources/app.asar/back-end/app.js:305:24)
at new App (/Applications/Publii.app/Contents/Resources/app.asar/back-end/app.js:70:14)
at App.<anonymous> (/Applications/Publii.app/Contents/Resources/app.asar/main.js:36:19)
at App.emit (events.js:215:7)
at App.EventEmitter.emit (domain.js:476:20)
at App.topLevelDomainCallback (domain.js:131:23)

**Comment by dziudek** [comment]
Hi,

It seems that your sites catalog cannot be created or not exists. Please check in your filesystem if `/Users/derin/Documents/Publii/sites` exists.

I have also added a more friendly message for such case.
