### ISSUE TITLE
Google cloud server upload not working

### ISSUE THREAD

**Issue by orthodoc** [GetPublii/Publii#917]
When I click on test connection, nothing happens and there is no error alert.

The `deployment-errors.log` reads like this:
```node
(node:21398) UnhandledPromiseRejectionWarning: TypeError: GoogleCloudStorage is not a function
    at GoogleCloud.initConnection (/Applications/Publii.app/Contents/Resources/app.asar/back-end/modules/deploy/google-cloud.js:35:19)
    at Deployment.initSession (/Applications/Publii.app/Contents/Resources/app.asar/back-end/modules/deploy/deployment.js:92:27)
    at process.<anonymous> (/Applications/Publii.app/Contents/Resources/app.asar/back-end/workers/deploy/deployment.js:10:28)
    at process.emit (events.js:210:5)
    at process.EventEmitter.emit (domain.js:476:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:21398) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:21398) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Publii version: v.0.37.3 (build 13870) beta

**Comment by dziudek** [comment]
Hi, we will address this issue in upcoming v.0.38

**Comment by orthodoc** [comment]
Thanks for looking into it.

Is there any other way of connecting to the server and uploading my files?

**Comment by dziudek** [comment]
@orthodoc - I suppose that you can temporary do it manually: https://cloud.google.com/storage/docs/uploading-objects - just please change your deployment method to "Manual" - then you will get the output files which you can upload anywhere you want (it is in fact a fallback deployment method in case of any deployment issues).

**Comment by orthodoc** [comment]
This is what I did
1. Use manual mode to get the output folder filled
2. Used gsutil to rsync the output folder with the Google storage bucket.

Now no worries. 🙂
