### ISSUE TITLE
Publii 0.38: missing libnode.so.64

### ISSUE THREAD

**Issue by pachainti** [GetPublii/Publii#941]
Hi,
I just updated publii to the latest version 0.38. Now I get this error under ubuntu and debian after installing the deb package.
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libnode.so.64: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/opt/Publii/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/Publii/resources/app.asar/node_modules/node-expat/lib/node-expat.js:4:32)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
```
It can be solved by installing the libnode64 package.

**Comment by dziudek** [comment]
Hi,

I have added this dependency to the list - I do hope that it will helps for others who has not this library installed :)
