### ISSUE TITLE
Publii 0.38 won't start on Fedora 33 Silverblue

### ISSUE THREAD

**Issue by Verhoeckx** [GetPublii/Publii#942]
Hello Publii developers,

I have bad news :wink:  : Publli 0.38 doesn't start on Fedora 33 Silverblue.

When I run Publii, I get the following error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libnode.so.64: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/usr/lib/opt/Publii/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/lib/opt/Publii/resources/app.asar/node_modules/node-expat/lib/node-expat.js:4:32)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
```

Publli 0.38 was installed with the following command:  
rpm-ostree install Publii-0.38.0.rpm

I think that the fact that I run Silverblue (ostree) doesn't matter but I can't be sure.

Hopefully the bug can be fixes. Let me know if you need more information.

**Comment by dziudek** [comment]
Hi,

Please instal libnode64 - it seems that for some reason linux ignores dependencies added as a rpm/deb package dependency: https://github.com/GetPublii/Publii/blob/master/package.json#L126-L139

Sometimes it works without any additional steps on other linux distros it requires this package to be installed..

**Comment by Verhoeckx** [comment]
Hi @dziudek,

That's quick :smile: !

I couldn't find the package `libnode64` anywhere so I installed the package `nodejs` instead. However that didn't do the trick :disappointed:.

Version 0.37.3 works fine. What's the difference?

**Comment by dziudek** [comment]
v.0.38 uses Electron 11 and as I suppose it is a reason of the problem - I will check if it can be related to the ASAR packaging

**Comment by dziudek** [comment]
@Verhoeckx - please check if these packages are working for you - I have removed node-expact which causes issue on Linux and I have replaced xml2json with fast-xml-parser which has no native dependencies:

https://dev-zen.com/publii-prerelease/

**Comment by Verhoeckx** [comment]
Yes, it works :partying_face: !

Perfect!! Thanks!!
  
  
I don't think it's important but for the sake of completeness I will report the following. When I run Publli I get the following warning:
`(node:7058) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information`

**Comment by dziudek** [comment]
Great news :) Regarding the notice - yes, I know - we will make a lot of changes to prepare for Electron 12 and future releases in v.0.39 :)

**Comment by Verhoeckx** [comment]
Thanks for solving the problem! I think this issue can closed now?

**Comment by dziudek** [comment]
@Verhoeckx - yes, v.0.38.1 will be released soon with few small fixes for linux too :)
